runtime:
  cache_dir: ./.cache/antora

site:
  title: GitOps Infrastructure Configuration Workshop
  url: https://alvarolop.github.io/workshop-gitops-infra/index.html
  start_page: workshop-gitops-infra::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/aolle/rhd-tutorial-ui/releases/download/v0.2.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./supplemental-ui
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

output:
  dir: ./gh-pages
